name: Check and create tag
on:
  workflow_dispatch:
  push:
    paths:
      - jetpytools/_version.py

jobs:
  new_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Get version number
        id: get_version
        run: echo "curr_ver=v$(uvx hatch version)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: ${{ steps.get_version.outputs.curr_ver }}

      - name: Make tag
        uses: actions/github-script@v8
        if: steps.check_tag.outputs.exists == 'false'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.get_version.outputs.curr_ver }}`,
              sha: context.sha
            })

      - name: Fallback
        if: steps.check_tag.outputs.exists == 'true'
        run: echo "Nothing to see here, move along citizen"
